github: [NormikChel, Normik-Chel]
patreon: NormikChel
open_collective:
ko_fi:
tidelift:
community_bridge:
liberapay:
issuehunt:
lfx_crowdfunding:
polar:
buy_me_a_coffee: normikchel
thanks_dev:
custom: [
  'https://www.donationalerts.com/r/normik_chel',
  'https://boosty.to/NormikChel/donate',
  'https://new.donatepay.ru/@NormikChel',
  'https://memealerts.com/NormikChel',
]
